# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Web Accessibility Initiative (WAI)"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Website of the World Wide Web Consortium’s Web Accessibility Initiative.
baseurl: "/wai-evaluation-tools-list" # the subpath of your site, e.g. /blog
url: "https://w3c.github.io" # the base hostname & protocol for your site
twitter:
  username: w3c_wai
author: w3c_wai
exclude:
  - "_external"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "w3c.json"

# Build settings
markdown: kramdown
kramwdown:
  toc_levels: 2..3
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
repository: w3c/wai-evaluation-tools-list

ytkey: AIzaSyCiZ9uToWu9jb7BTx47NtzCvmGGXKXp8nI

remote_theme: w3c/wai-website-theme

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      standalone_resource_doc_name: List of Evaluation Tools
      footer: >
         <p><strong>Date:</strong> Information on specific tools is updated frequently, as we receive it. In the information for each tool there is a last updated date. The Evaluation Tools List user interface was updated on 5 Dec 2023. First published March 2006.</p>
         <p><strong>Editors:</strong> <a href="https://www.w3.org/People/kevin/">Kevin White</a>, Michel Hansma and Vera Lange. Contributors: Eric Velleman, Steve Lee, Wilco Fiers, Shawn Henry, Brent Bakken, Sharron Rush, Kris Anne Kinney, Steve Lee, Daniel Montavo, Estella Oncins, Michele Williams, Vicki Menezes Miller, Andrew Arch, Laura Keen, Sylvie Duchateau, Jade Matos Carew, Brian Elton, Howard Kramer, Mark Palmer, Shadi Abou-Zahra, and other <a href="https://www.w3.org/groups/wg/eowg/participants">EOWG Participants</a>.</p>
         <p><strong>Content Maintainer:</strong> José Ramón Hilera González</p>
         <p>Developed by the Accessibility Education and Outreach Working Group (<a href="http://www.w3.org/WAI/EO/">EOWG</a>). Developed as part of the <a href="https://www.w3.org/WAI/about/projects/wai-coop/">WAI-CooP project</a>, co-funded by the European Commission.</p>
         <p>Previous Editors/Developers: Eric Eggert and Shadi Abou-Zahra. <a href="https://www.w3.org/WAI/ER/tools/acknowledgements">Acknowledgements</a> lists contributors and previous editors. Developed with support from the <a href="https://www.w3.org/WAI/TIES/">WAI-TIES Project</a> in 2006, and updated with support from the <a href="https://www.w3.org/WAI/ACT/">WAI-ACT Project</a> in 2014
         
#  -
#    scope:
#      path: "_business-case"
#    values:
#      layout: "sidenav"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-remote-theme
  - wai-website-plugin